version: '3.8'
services:
  api:
    build:
      context: .
    environment:
      MYSQL_HOST: $MYSQL_HOST
      CONTAINER_PORT: $CONTAINER_PORT
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MAILGRID_API_KEY: $MAILGRID_API_KEY
    ports:
      - "${HOST_PORT}:${CONTAINER_PORT}"
    volumes:
      - .:/auth-nest
    depends_on:
      - mysql
    command: yarn run start:dev

  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - /var/lib/mysql
